### ISSUE TITLE
File "NMscript.py", line 484, in <module>     nmap()

### ISSUE THREAD

**Issue by m0nd4y99** [cabesonwiliams/NMscript-EN-#1]
Traceback (most recent call last):
  File "NMscript.py", line 484, in <module>
    nmap()
  File "NMscript.py", line 95, in nmap
    print(banner3)
  File "C:\Users\Milboro\AppData\Local\Programs\Python\Python38\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode characters in position 28-31: character maps to <undefined>

**Comment by cabesonwiliams** [comment]
I really don't know what your problem is, friend, try reinstalling the tool
